Repository tijlleenders/ZinZen-scheduler, pull requests merged in 2023-11, with the labels that each got.

#399 refactor: clean code
  src/models/utils.rs
Labels: clean code

#400 refactor: test generation
  build.rs
  build_templates/run_test.rs
  build_templates/test_fn.rs
  build_templates/test_fn_experimental.rs
  build_templates/test_fn_stable.rs
  build_templates/tests_mod.rs
Labels: clean code

#402 refactor: make Repetition enum more readable
  src/models/budget/impls.rs
  src/models/repetition.rs
  src/models/slots_iterator/utils.rs
  src/services/budgeting.rs
  src/services/preprocess.rs
Labels: clean code

#401 refactor: improved readability
  .editorconfig
  .github/workflows/rust.yml
  .rustfmt.toml
  Cargo.toml
  src/lib.rs
Labels: clean code

#405 Rom/ /date normalization
  src/models/budget/impls.rs
  src/models/budget/mod.rs
  src/models/date.rs
  src/models/input.rs
  src/models/mod.rs
  src/models/output.rs
  src/models/slot/impls.rs
  src/models/slot/mod.rs
  src/models/timeline/mod.rs
  src/services/flexibility.rs
  src/services/output.rs
  src/services/placer/conflicts.rs
  src/services/placer/mod.rs
  src/services/splitters.rs
  src/tests/slot.rs
Labels: clean code

#404 Rom/ /clean code
  src/models/goal/impls.rs
  src/models/goal/mod.rs
  src/services/filter/filter_on_days.rs
  src/services/filter/mod.rs
  src/tests/general.rs
  todos.md
Labels: clean code

#407 added cargo check script file to do all the checks before pushing to …
  scripts/cargo-check.sh
Labels: enhancement

#416 add branching convention to docs
  CONTRIBUTING.md
  documentation/technical/Readme.md
Labels: devex

#421 add pr-template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: devex
